### ISSUE TITLE
Routing Name Title not changing on uploading on server

### ISSUE THREAD

**Issue by Sachin124** [creativetimofficial/ct-material-dashboard-pro-angular#309]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Angular 6 ] I am running the latest version
- [Y ] I checked the documentation and found no answer
- [Y ] I checked to make sure that this issue has not already been filed
- [Y ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
On localhost is working fine. 
![img_20190101](https://user-images.githubusercontent.com/26019527/50570964-c536d680-0dc3-11e9-812e-adefec50a99f.png)
![img_20190101 1](https://user-images.githubusercontent.com/26019527/50570965-c536d680-0dc3-11e9-9a14-f8df540f3499.png)
# Current Behavior

![server](https://user-images.githubusercontent.com/26019527/50570976-0d55f900-0dc4-11e9-817d-d6fc79a7e4e0.png)

What is the current behavior?
When I upload On my server then activated route is  not displaying. 
In  your demo also not showing on activated path
please check:   https://demos.creative-tim.com/material-dashboard-pro-angular2/dashboard
When I change my routeerlink still every page has shown dashboard.

**Comment by chelaruc** [comment]
@Sachin124 Sorry for the late response. If you go in `src/app/shared/navbar/navbar.component.ts` file and check the `getTitle` function. On our local repository, this is working. I think it didn't work on the live demo because of the path and you need to change the function to match your requirements. If you can send me your archive at ciprian@creative-tim.com, I can help you more.
