### ISSUE TITLE
[Bug] Jquery doesn't work Edge

### ISSUE THREAD

**Issue by patrykstepien** [creativetimofficial/ct-material-dashboard-pro-angular#339]
### Version
2.3.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/dashboard
### Operating System
Windows 10
## Browser & Version
Edge 18
### Steps to reproduce
When I test demo I can't use notifications and other components which use jQuery. 

### What is actually happening?
Jquery doesn't work

---
### Solution
Probably, problem is with bootstrap-material-design beacuse when I deleted it from scripts from angular.json jquery works, beacuse I can log version of jQuery.

**Comment by chrisjcalderon** [comment]
The app does not work at all in Internet Explorer (Edge or 11) - it throws a JQuery Error:

 ERROR ReferenceError: '$' is not defined

**Comment by chelaruc** [comment]
@patrykstepien @chrisjcalderon 
As we said in README.md, we don't support Internet Explorer, but I think the error is because of jQuery initialization. You need to replace all the declare const $: any; with declare var $: any; and in angular.json file replace "node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.min.js", with "node_modules/bootstrap/dist/js/bootstrap.js",

**Comment by chelaruc** [comment]
@chrisjcalderon it works with the modifications I've told to you?

**Comment by chrisjcalderon** [comment]
It did work, thanks much for the help

**Comment by nbetcher** [comment]
@chelaruc Is the 'declare const' replacement with 'declare var' really necessary? After replacing 'bootstrap-material-design's js include with bootstrap's in angular.json, all issues seem to be resolved in Edge, including the error about '$' being undefined. I do have an extremely outdated Edge (42.17134.1098.0) though, and am unable to test on a newer one.
