### ISSUE TITLE
main.ts is part of the TypeScript compilation but it's unused. Add only entry points to the 'files' or 'include' properties in your tsconfig.

### ISSUE THREAD

**Issue by felixchacaliaza** [creativetimofficial/ct-material-dashboard-pro-angular#370]
as the title says, any solution?

**Comment by EINazare** [comment]
Hello there, @felixchacaliaza ,

Thank you for your interest in working with our products.
We are sorry, but we have to close your issue since we haven't found the problem that you speak of (this means you have a different OS or different NodeJS version, or you've made changes to our product and we need to follow some steps to reproduce your issue, all these will be answered by following our bellow rules), and also, you haven't followed our rules for opening an issue:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

 https://www.creative-tim.com/new-issue/material-dashboard-pro-angular2

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
By the end of this week, we will add an automated bot, that will auto-close these kinds of issues, and we will not see them anymore and no answer will be given.

Please use the above link to open a propper Github issue with all the necessary information that we need to reproduce it.

Best,
Manu
